[package]
name = "prepare_builds"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5" }
clap_derive = { version = "4.5" }
tera = "1.20"
ron = "0.10"
serde = { version = "1", features = ["derive"] }
